# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: prompt.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'prompt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cprompt.proto\"\x1d\n\x0cLevelRequest\x12\r\n\x05level\x18\x01 \x01(\x05\" \n\x0ePromptResponse\x12\x0e\n\x06prompt\x18\x01 \x01(\t2<\n\rPromptService\x12+\n\tGetPrompt\x12\r.LevelRequest\x1a\x0f.PromptResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'prompt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LEVELREQUEST']._serialized_start=16
  _globals['_LEVELREQUEST']._serialized_end=45
  _globals['_PROMPTRESPONSE']._serialized_start=47
  _globals['_PROMPTRESPONSE']._serialized_end=79
  _globals['_PROMPTSERVICE']._serialized_start=81
  _globals['_PROMPTSERVICE']._serialized_end=141
# @@protoc_insertion_point(module_scope)
